### ISSUE TITLE
Wait trong Webdriver

### ISSUE THREAD

**Issue by jacobvn84** [nhungpham1512/automation_testing_beginner#13]
WebDriver can generally be said to have a blocking API. Because it is an out-of-process library that instructs the browser what to do, and because the web platform has an intrinsically asynchronous nature, WebDriver does not track the active, real-time state of the DOM. This comes with some challenges that we will discuss here.

https://www.selenium.dev/documentation/webdriver/waits/

**Comment by jacobvn84** [comment]
serenity.conf

```
webdriver {
  #timeouts.implicitlywait=60000
  wait.for.timeout=90000
}

```

**Comment by nhungpham1512** [comment]
có 3 loại wait trong serenity
+ Implicit wait
vd ở trên
+ Explicit wait
`               actor.attemptsTo(
                Open.url("https://demo.nopcommerce.com/login?returnUrl=%2F"),
                //WaitUntil.the(REGISTERS, isPresent()).forNoMoreThan(6).seconds(),
                Click.on(REGISTERS).afterWaitingUntilPresent(),
                Click.on("//select[@name='DateOfBirthDay']")
        );`
+ FluentWait
vd: [link](https://www.selenium.dev/documentation/webdriver/waits/)
