### ISSUE TITLE
DRY Principle 

### ISSUE THREAD

**Issue by jacobvn84** [nhungpham1512/automation_testing_beginner#3]
"Don't repeat yourself" (DRY) is a [principle](https://en.wikipedia.org/wiki/Principle#Principle_as_axiom_or_logical_fundament) of [software development](https://en.wikipedia.org/wiki/Software_development_process) aimed at reducing repetition of [information](https://en.wikipedia.org/wiki/Information_theory) which is likely to change, replacing it with [abstractions](https://en.wikipedia.org/wiki/Information_hiding) that are less likely to change, or using [data normalization](https://en.wikipedia.org/wiki/Data_normalization) which avoids redundancy in the first place.

The DRY principle is stated as "Every piece of knowledge must have a single, unambiguous, authoritative representation within a system". The principle has been formulated by [Andy Hunt](https://en.wikipedia.org/wiki/Andy_Hunt_(author)) and [Dave Thomas](https://en.wikipedia.org/wiki/Dave_Thomas_(author)) in their book [The Pragmatic Programmer](https://en.wikipedia.org/wiki/The_Pragmatic_Programmer).[[1]](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself#cite_note-1) They apply it quite broadly to include [database schemas](https://en.wikipedia.org/wiki/Database_schema), [test plans](https://en.wikipedia.org/wiki/Test_plan), the [build](https://en.wikipedia.org/wiki/Software_build) system, even [documentation](https://en.wikipedia.org/wiki/Software_documentation).[[2]](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself#cite_note-HuntThomasBroadInfo-2) When the DRY principle is applied successfully, a modification of any single element of a system does not require a change in other logically unrelated elements. Additionally, elements that are logically related all change predictably and uniformly, and are thus kept in [sync](https://en.wikipedia.org/wiki/Synchronization). Besides using [methods](https://en.wikipedia.org/wiki/Method_(computer_science)) and [subroutines](https://en.wikipedia.org/wiki/Subroutine) in their code, Thomas and Hunt rely on [code generators](https://en.wikipedia.org/wiki/Automatic_programming), automatic build systems, and [scripting languages](https://en.wikipedia.org/wiki/Scripting_language) to observe the DRY principle across layers.

**Comment by jacobvn84** [comment]
Lặp lại những thứ có thể nhìn thấy
Lặp lại những thứ không nhìn thấy 

Ví dụ và bài học.

**Comment by nhungpham1512** [comment]
Sử dụng **refactor** đến dọn dẹp gọn gàng lại code. Mục đích khi muốn thay đổi nó, chỉ cần thay đổi 1 chỗ duy nhất cho tất cả các chỗ trong code, thay vì đi tìm từng chỗ và copy paste lại chúng
1. Rename
2. Introduce Contanst, Introduce Field, Introduce Parameter,...
3. Move member
